# Generated by Django 5.0.6 on 2024-08-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_listings_realtor_delete_listing"),
        ("realtors", "0003_realtor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="realtor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="realtors.realtor"
            ),
        ),
    ]
