# Generated by Django 5.0.6 on 2024-08-14 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listings_remove_listing_realtor"),
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Realtors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("description", models.TextField(blank=tuple)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("is_mvp", models.BooleanField(default=False)),
                (
                    "hire_date",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Realtor",
        ),
    ]
