# Generated by Django 5.0.6 on 2024-08-14 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_alter_listings_realtor"),
        ("realtors", "0003_realtor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Realtors",
        ),
    ]
